@echo off
REM ###########################################################################
REM Script generated by HPE Security Fortify SCA Scan Wizard (c) 2011-2017 Hewlett Packard Enterprise Development LP
REM Created on 2017/08/21 15:23:45
REM ###########################################################################
REM Generated for the following languages:
REM 	C#.NET / VB.NET
REM 	HTML
REM 	Javascript
REM 	XML
REM ###########################################################################
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM FPR - the name of analysis result file
REM BUILDID - the SCA build id
REM ARGFILE - the name of the argument file that's extracted and passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java Bytecode translation that's extracted and passed to SCA
REM MEMORY - the memory settings for SCA
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="FortifyTeamCityHPFortifyDemo.fpr"
set BUILDID="TeamCityHPFortifyDemo"
set ARGFILE="FortifyTeamCityHPFortifyDemo.bat.args"
set BYTECODE_ARGFILE="FortifyTeamCityHPFortifyDemo.bat.bytecode.args"
set MEMORY=-Xmx2388M -Xms400M -Xss24M 
set LAUNCHERSWITCHES=""
set OLDFILENUMBER=FortifyTeamCityHPFortifyDemo.bat.fileno
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false

set PROJECTROOT0="C:\Users\Krishna\Source\Repos\TeamCityHPFortifyDemo"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################

echo Searching .NET Framework Version...
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.6.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.6.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6" (
set LAUNCHERSWITCHES=-dotnet-version 4.6 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.5.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.5.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5" (
set LAUNCHERSWITCHES=-dotnet-version 4.5 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0" (
set LAUNCHERSWITCHES=-dotnet-version 4.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.0
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5" (
set LAUNCHERSWITCHES=-dotnet-version 3.5 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 3.5
GOTO DOTNETSELECTED
)
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0" /v Install 2>NUL >NUL
IF %ERRORLEVEL%==0 (
set LAUNCHERSWITCHES=-dotnet-version 3.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 3.0
GOTO DOTNETSELECTED
)
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727" /v Install 2>NUL >NUL
IF %ERRORLEVEL%==0 (
set LAUNCHERSWITCHES=-dotnet-version 2.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 2.0
GOTO DOTNETSELECTED
)
:DOTNETSELECTED
REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -quick -scan -f %FPR%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.AI.Agent.Intercept.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.AI.DependencyCollector.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.AI.PerfCounterCollector.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.AI.ServerTelemetryChannel.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.AI.Web.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.AI.WindowsServer.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.ApplicationInsights.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Microsoft.Web.Infrastructure.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\HPFortyfyDemo\bin\roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\roslyn\Microsoft.CodeAnalysis.CSharp.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\roslyn\Microsoft.CodeAnalysis.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\roslyn\Microsoft.CodeAnalysis.VisualBasic.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\roslyn\System.Collections.Immutable.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\HPFortyfyDemo\bin\roslyn\System.Reflection.Metadata.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.Helpers.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.Mvc.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.Optimization.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.Razor.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.WebPages.Deployment.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.WebPages.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\System.Web.WebPages.Razor.dll;PROJECTROOT0_MARKER\HPFortyfyDemo\bin\WebGrease.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.2.0.0\lib\dotnet5.4\Microsoft.ApplicationInsights.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.2.0.0\lib\net40\Microsoft.ApplicationInsights.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.2.0.0\lib\net45\Microsoft.ApplicationInsights.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.2.0.0\lib\net46\Microsoft.ApplicationInsights.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.Agent.Intercept.1.2.1\lib\net40\Microsoft.AI.Agent.Intercept.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.Agent.Intercept.1.2.1\lib\net45\Microsoft.AI.Agent.Intercept.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.DependencyCollector.2.0.0\lib\net40\Microsoft.AI.DependencyCollector.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.DependencyCollector.2.0.0\lib\net45\Microsoft.AI.DependencyCollector.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.PerfCounterCollector.2.0.0\lib\net40\Microsoft.AI.PerfCounterCollector.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.PerfCounterCollector.2.0.0\lib\net45\Microsoft.AI.PerfCounterCollector.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.Web.2.0.0\lib\net40\Microsoft.AI.Web.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.Web.2.0.0\lib\net45\Microsoft.AI.Web.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.WindowsServer.2.0.0\lib\net40\Microsoft.AI.WindowsServer.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.WindowsServer.2.0.0\lib\net45\Microsoft.AI.WindowsServer.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.0.0\lib\net40\Microsoft.AI.ServerTelemetryChannel.dll;PROJECTROOT0_MARKER\packages\Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.0.0\lib\net45\Microsoft.AI.ServerTelemetryChannel.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Microsoft.AspNet.Mvc.5.2.3\lib\net45\System.Web.Mvc.dll;PROJECTROOT0_MARKER\packages\Microsoft.AspNet.Razor.3.2.3\lib\net45\System.Web.Razor.dll;PROJECTROOT0_MARKER\packages\Microsoft.AspNet.Web.Optimization.1.1.3\lib\net40\System.Web.Optimization.dll;PROJECTROOT0_MARKER\packages\Microsoft.AspNet.WebPages.3.2.3\lib\net45\System.Web.Helpers.dll;PROJECTROOT0_MARKER\packages\Microsoft.AspNet.WebPages.3.2.3\lib\net45\System.Web.WebPages.Deployment.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Microsoft.AspNet.WebPages.3.2.3\lib\net45\System.Web.WebPages.dll;PROJECTROOT0_MARKER\packages\Microsoft.AspNet.WebPages.3.2.3\lib\net45\System.Web.WebPages.Razor.dll;PROJECTROOT0_MARKER\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0\lib\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll;PROJECTROOT0_MARKER\packages\Microsoft.Net.Compilers.1.0.0\tools\Microsoft.Build.Tasks.CodeAnalysis.dll;PROJECTROOT0_MARKER\packages\Microsoft.Net.Compilers.1.0.0\tools\Microsoft.CodeAnalysis.CSharp.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Microsoft.Net.Compilers.1.0.0\tools\Microsoft.CodeAnalysis.dll;PROJECTROOT0_MARKER\packages\Microsoft.Net.Compilers.1.0.0\tools\Microsoft.CodeAnalysis.VisualBasic.dll;PROJECTROOT0_MARKER\packages\Microsoft.Net.Compilers.1.0.0\tools\System.Collections.Immutable.dll;PROJECTROOT0_MARKER\packages\Microsoft.Net.Compilers.1.0.0\tools\System.Reflection.Metadata.dll;PROJECTROOT0_MARKER\packages\Microsoft.Web.Infrastructure.1.0.0.0\lib\net40\Microsoft.Web.Infrastructure.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\net20\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\net35\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\net40\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\net45\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\netcore45\Newtonsoft.Json.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\portable-net40%2Bsl5%2Bwp80%2Bwin8%2Bwpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\packages\Newtonsoft.Json.6.0.4\lib\portable-net45%2Bwp80%2Bwin8%2Bwpa81\Newtonsoft.Json.dll;PROJECTROOT0_MARKER\packages\WebGrease.1.5.2\lib\WebGrease.dll"
REM ARGS "PROJECTROOT0_MARKER"
